>- #theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs@v0.3.3
plugins:
  - jekyll-feed
  - jekyll-remote-theme

title: Just blog
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This site tests some features of Just the Docs, a remote theme for Jekyll on GitHub Pages.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

defaults:
  -
    scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
